services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - patientor-frontend
      - patientor-backend

  patientor-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/patientor/frontend
      - /usr/patientor/frontend/node_modules
    container_name: patientor-frontend

  patientor-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/patientor/backend
    container_name: patientor-backend